export const routes = {
  signIn: '/sign-in',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  register: '/register',
  dashboard: '/',
  stands: '/stands',
  stock: '/stock',
  leads: '/leads',
  bookings: '/bookings',
  insights: '/insights',
  chats: '/chats',
  billing: '/billing',
  team: '/team',
  account: '/account',
} as const
